### ISSUE TITLE
Possible bug in gplay.c

### ISSUE THREAD

**Issue by 2bt** [drfiemost/goattracker2#3]
Hi there! Do you know if this could be a bug?
https://github.com/drfiemost/goattracker2/blob/ca551fac770b95ae768af74f559c2516aaaa35ff/src/gplay.c#L334
It looks like this line should read loke so
```c++
if (cptr->gatetimer > cptr->tick)
```

**Comment by drfiemost** [comment]
Yes, it looks like. chn is an array and always points to the first channel
