### ISSUE TITLE
Will not start

### ISSUE THREAD

**Issue by dhry** [drfiemost/goattracker2#5]
Not sure if I'm doing anything obviously wrong, but when I try to start goattrk2.exe (20210801 build) the window pops up momentarily, then disappears and the app quits. Windows 10 21H1, Ryzen 9 3950X, 64Gb RAM.

Event viewer says the following:

**Faulting application name: goattrk2.exe, version: 0.0.0.0, time stamp: 0x6106bb2a
Faulting module name: msvcrt.dll, version: 7.0.19041.546, time stamp: 0x564f9f39
Exception code: 0xc0000005
Fault offset: 0x000000000002b034
Faulting process id: 0x8334
Faulting application start time: 0x01d787d0c25d1e07
Faulting application path: J:\GoatTracker_Fork\goattrk2.exe
Faulting module path: C:\Windows\System32\msvcrt.dll
Report Id: 0b9c945a-d4d8-4d65-a7a1-79c494e5de3a
Faulting package full name: 
Faulting package-relative application ID:**

Am I missing a runtime?

Dhry

**Comment by drfiemost** [comment]
I'm on an Intel i7 with Windows 10 Pro 20H2 and it works ok.
Maybe a **Data Execution Protection** problem?
Are you using an existing goattrk2.cfg?

**Comment by drfiemost** [comment]
@dhry any news? I cannot reproduce the issue, it works fine with Wine on Linux too. Might redirect the question to msys in case.

**Comment by drfiemost** [comment]
Reopen if the problem persists.
